version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: task-todo-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: task-todo-postgres-data

networks:
  task-todo-network:
    driver: bridge
